export const USER_DETAIL = 'USER_DETAIL'
export const USER_UPDATE = 'USER_UPDATE'
export const USER_FOLLOW = 'USER_FOLLOW'
export const USER_UN_FOLLOW = 'USER_UN_FOLLOW'
export const CURRENT_USER_DETAIL = 'CURRENT_USER_DETAIL'
export const CURRENT_USER_MORE_INFO = 'CURRENT_USER_MORE_INFO'

export const TOPIC_DETAIL = 'TOPIC_DETAIL'
export const TOPIC_FOLLOW = 'TOPIC_FOLLOW'
export const TOPIC_UN_FOLLOW = 'TOPIC_UN_FOLLOW'

export const TOPIC_FOLLOW_USER = 'TOPIC_FOLLOW_USER'
export const TOPIC_UN_FOLLOW_USER = 'TOPIC_UN_FOLLOW_USER'
export const TOPIC_LIKE = 'TOPIC_LIKE'
export const TOPIC_UN_LIKE = 'TOPIC_UN_LIKE'

